services: 
  mongodb-dev: 
    environment: 
      MONGO_INITDB_DATABASE: test # database name to give
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    image: mongo
    container_name: mongo
    ports: 
      - "27017-27019:27017-27019"
      
    mh-account:
        environment:
            DB_URL: mongodb://root:root@localhost:27017
            DB: test 
        image: superdeano/mh-account:0.0.0
        depends_on: mongo 
        
          
version: "3"

